import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { useEffect } from "react";
import { axiosInstance } from "@/config/axiosInstance";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const checkUserAuth = async () => {
    try {
      const response = await axiosInstance({
        method: "GET",
        url: "/authentication/verify-auth"
      })
      console.log(response, "===reponse")
    } catch (error) {
      console.log(error)
    }
  }

  useEffect(()=>{
    checkUserAuth()
  },[])

  return (
    <html lang="en">
      <body
        
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
